In [15]:
# utilizado para manejos de directorios y rutas
import os

# Computacion vectorial y cientifica para python
import numpy as np

# Librerias para graficación (trazado de gráficos)
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D  # Necesario para graficar superficies 3D

# llama a matplotlib a embeber graficas dentro de los cuadernillos
%matplotlib inline

In [16]:
# Cargar datos
data = np.loadtxt('/content/DATASET_Autos.txt', delimiter=',',max_rows=100)
X, y = data[:,:7], data[:,7]


m = y.size

In [17]:
X

array([[2.000e+00, 2.011e+03, 2.000e+00, 4.000e+00, 2.000e+00, 1.000e+00,
        2.000e+00],
       [2.000e+00, 2.016e+03, 3.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
        2.000e+00],
       [2.000e+00, 2.016e+03, 2.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
        2.000e+00],
       [2.000e+00, 2.016e+03, 2.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00],
       [2.000e+00, 2.017e+03, 2.000e+00, 4.000e+00, 1.000e+00, 2.000e+00,
        2.000e+00],
       [2.000e+00, 2.016e+03, 3.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
        2.000e+00],
       [2.000e+00, 2.014e+03, 2.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
        2.000e+00],
       [2.800e+01, 2.015e+03, 1.000e+00, 5.000e+00, 2.000e+00, 1.000e+00,
        2.000e+00],
       [2.000e+00, 2.016e+03, 3.000e+00, 4.000e+00, 2.000e+00, 1.000e+00,
        2.000e+00],
       [2.000e+00, 2.014e+03, 3.000e+00, 4.000e+00, 1.000e+00, 1.000e+00,
        2.000e+00],
       [2.600e+01, 2.016e+03, 1.000e+00, 2.000e+00, 1.000e+0

In [18]:
y

array([   99856.,   977011.,   977011.,    95546.,   948275.,    81178.,
         797413.,  7248253.,    60345.,   574713.,    53017.,   431034.,
        4141859.,   413793.,   387931.,   372126.,   352011.,   341954.,
         327586.,   301724.,    28592.,    27155.,   228448.,   214080.,
          19397.,  1435344., 12908793.,   145000.,   128000.,   125000.,
          99900.,    92897.,    85000.,    79500.,    78500.,    78500.,
          78500.,    75000.,    75000.,    74900.,    74900.,    73000.,
          72261.,    70900.,    69000.,    69000.,    67000.,    67000.,
          66800.,    66800.,    66500.,    65000.,    65000.,    65000.,
          63800.,    62000.,    60900.,    60000.,    60000.,    58500.,
          58000.,    57800.,    57800.,    57000.,    56990.,    56990.,
          56000.,    56000.,    55800.,    55800.,    55800.,    55800.,
          55000.,    54500.,    54500.,    54500.,    51500.,    50000.,
          50000.,    50000.,    49500.,    49000., 

In [19]:
def  featureNormalize(X):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu) / sigma
    
    return X_norm, mu, sigma

In [20]:
X =np.asarray(X)
Y=np.asarray(y)
X_norm, mu, sigma = featureNormalize(X)

#print(X_norm)


In [21]:
# No olvidarse agregar unos a la matriz de x
#X = np.stack([np.ones(m), X], axis=1)
#X_norm = np.concatenate([np.ones((m,1)), X_norm], axis=1)
X = np.concatenate([np.ones((m,1)), X_norm], axis=1)
#=np.insert(X,0,1, axis=1)
X

array([[ 1.        , -0.96363785, -0.93243034, -0.09082573, -0.48189987,
         1.88293774, -0.34956332,  0.62360956],
       [ 1.        , -0.96363785,  0.14179816,  1.42293638, -0.48189987,
        -0.531085  , -0.34956332,  0.62360956],
       [ 1.        , -0.96363785,  0.14179816, -0.09082573, -0.48189987,
        -0.531085  , -0.34956332,  0.62360956],
       [ 1.        , -0.96363785,  0.14179816, -0.09082573, -0.48189987,
        -0.531085  , -0.34956332, -1.60356745],
       [ 1.        , -0.96363785,  0.35664386, -0.09082573, -0.48189987,
        -0.531085  ,  2.14731753,  0.62360956],
       [ 1.        , -0.96363785,  0.14179816,  1.42293638, -0.48189987,
        -0.531085  , -0.34956332,  0.62360956],
       [ 1.        , -0.96363785, -0.28789324, -0.09082573, -0.48189987,
        -0.531085  , -0.34956332,  0.62360956],
       [ 1.        ,  2.73718699, -0.07304754, -1.60458783,  0.89495691,
         1.88293774, -0.34956332,  0.62360956],
       [ 1.        , -0.96363785

In [22]:
def normalEqn(X, y):
  
    theta = np.zeros(X.shape[1])
    
    theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T,X)),X.T),y)
    
    return theta

In [23]:
# Calcula los parametros con la ecuación de la normal
theta = normalEqn(X, y);

# Muestra los resultados optenidos a partir de la aplicación de la ecuación de la normal
print('Theta calculado a partir de la ecuación de la normal: {:s}'.format(str(theta)));

# Estimar el precio para un auto

X_array = [1,2,2015,2,4,2,1,2]
price = np.dot(X_array, theta) 

print('Precio predecido para un auto usando la ecuación de la normal): ${:.0f}'.format(price))

Theta calculado a partir de la ecuación de la normal: [ 383899.73000001  270995.20929555 -337364.29265369  162080.02034622
  196251.63467819   73049.77406241  -45101.62237115  100237.91149399]
Precio predecido para un auto usando la ecuación de la normal): $-677452519


In [27]:
# Calcula los parametros con la ecuación de la normal
theta = normalEqn(X, y);

# Muestra los resultados optenidos a partir de la aplicación de la ecuación de la normal
print('Theta calculado a partir de la ecuación de la normal: {:s}'.format(str(theta)));

# Estimar el precio para un auto

X_norm = [1,20,2012,1,5,1,1,2]
X_norm[1:8]= (X_norm[1:8] - mu) / sigma
price = np.dot(X_norm, theta) 

print('Precio predecido para un auto usando la ecuación de la normal): ${:.0f}'.format(price))

Theta calculado a partir de la ecuación de la normal: [ 383899.73000001  270995.20929555 -337364.29265369  162080.02034622
  196251.63467819   73049.77406241  -45101.62237115  100237.91149399]
Precio predecido para un auto usando la ecuación de la normal): $1014210


In [29]:
X_array = [1,20,2012,1,5,1,1,2]
X_array[1:8]= (X_array[1:8] - mu) / sigma

In [30]:
X_array[1:8]

[1.5984716529478473,
 -0.7175846399657881,
 -1.6045878312381827,
 0.8949569080679688,
 -0.5310850045437946,
 -0.34956331860724515,
 0.623609564462324]